### ISSUE TITLE
[Android] - allow users to input places and addresses

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#1]
example - if i want to be picked up from a Ralph's grocery store and be taken to Walmart.
-if i don't know the address of the place i'm at or going but i know the name

**Comment by trietphamvm** [comment]
will research more and add this feature in future @phuong37. Currently we are using Google Map, still not sure Google support this.

**Comment by phuong37** [comment]
ok, thank you anh @trietphamvm!

**Comment by cuong-ubesim** [comment]
It looks like that Google Places API supports some other types we can use in pick-up and drop-off autocomplete textboxes. For now, Android app are using geocode type.

Please refer to https://developers.google.com/places/supported_types and https://developers.google.com/places/web-service/autocomplete for more details.

**Comment by phuong37** [comment]
thanks anh @cuong-ubesim - that sounds good

**Comment by phuong37** [comment]
feature added so closing this enhancement. if we have issues with search, we will refer to document before we log. thank you!
