### ISSUE TITLE
[Android] - unable to add american express card

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#10]
-it only allows me to enter 14 digits. my american express card has 15 digits.

**Comment by nguyendtt** [comment]
How do I test this @ThangPk ? Should I just put in 4242 4242 4242 424?

**Comment by phuong37** [comment]
chi @nguyendtt - try this https://stripe.com/docs/testing

**Comment by nguyendtt** [comment]
This is now resolved.
