### ISSUE TITLE
[Android] - able to add US number to different country

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#11]
should we add country validation for the phone numbers?
![image](https://cloud.githubusercontent.com/assets/14874365/10138856/8d2f71b4-662a-11e5-8faa-a29f790e2375.png)

**Comment by trietphamvm** [comment]
This is a big issue, we can't validate all format of the phone number for all countries. When we go live, we will limit the phone for US only

**Comment by phuong37** [comment]
for now, that's perfect! thanks!

**Comment by nguyendtt** [comment]
I agree.  I opened a similar bug for iOS as well.

**Comment by nguyendtt** [comment]
Drop down to choose different countries is not available anymore.  Only US is present. Closing.
