### ISSUE TITLE
[Android] - sign-in with facebook from home screen does not connect to facebook

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#12]
it looks like it's trying to connect but then just goes back to the home screen and does nothing.

**Comment by ThangPk** [comment]
@nguyendtt Could you please help to check it again? It an issue of facebook haskey when configuring for app release. Thanks.

**Comment by nguyendtt** [comment]
@ThangPk I'm not able to get the app to work on the 2 Androids that I have (there's a bug logged for that.) @phuong37 would you kindly check when you have some time? Thanks.

**Comment by ThangPk** [comment]
@nguyendtt Did you register account facebook? Could you please share the message of the log in failed?

**Comment by nguyendtt** [comment]
i haven't able to use the app on my Android phones @ThangPk .  I do have a facebook account but could only try to connect on the iPhone.  The message is just "Please wait...."

**Comment by phuong37** [comment]
anh @ThangPk and chi @nguyendtt - sorry, i didn't get notified of this. the "sign-in with facebook" button on the home screen gave me an error that said "Login failed, email or password is invalid. Try again!" is it supposed to use single sign-on and pop up a facebook dialogue?

the "sign-up with facebook" button on the create a profile screen worked though!

**Comment by nguyendtt** [comment]
I was just able to check out the app on Android and experienced the same issue that @phuong37  experienced for login in with Facebook.  Same error message from the home screen but it seems to work fine on the create a profile screen.  I'm unsure how this should work so if @ThangPk or @cuong-ubesim can walk us through how to test this, that would be great. Thanks.

**Comment by ThangPk** [comment]
@phuong37 @nguyendtt 

We got the error message from home screen "Login failed, email or password is invalid" due to no signing up facebook account. Please try to sign up a new account with facebook (Create profile screen) and try again. Thanks.

**Comment by phuong37** [comment]
anh @ThangPk - i've tried signing up (creating a profile) first but keep getting the error "Error happen. Please try again" on the payment screen. It's not letting complete the registration using Facebook. As for signing in with Facebook, is it not possible to sign-in with Facebook before creating a profile? If it's not possible, we need to remove for all first time users.

**Comment by nguyendtt** [comment]
I'm now able to sign on with Facebook through Create a Profile and get past the payment screen on Android.  After logging out, i'm now able to log back in using FB from the homescreen. I agree with @phuong37  that this is really confusing to users.  They should be able to click on "Sign in with Facebook" from Homescreen or Create a Profile regardless if they already have an account or not.  If they click on "Sign in with Facebook" from Homescreen and they don't already have an account, it should make the connection with Facebook and bring user back to the Create a Profile screen with their FB profile prepopulated.  What do you think, @trietphamvm @ThangPk ?  Another thing is that, after DAR made the connection with FB, before returning me to the rider screen, I received this confirmation "You have already authorized DealARide" (see attached, sorry for bad picture) regardless if I'm a returned user or a first-time user.  Is this step necessary and can we eliminate it?

**Comment by nguyendtt** [comment]
![image](https://cloud.githubusercontent.com/assets/14857908/10270203/daf12df8-6aa7-11e5-922a-103efc7810ea.jpg)

**Comment by cuong-ubesim** [comment]
Agreed chi @nguyendtt . Will include this enhancement in next build. Thanks!

**Comment by cuong-ubesim** [comment]
If they click on "Sign in with Facebook" from Homescreen and they don't already have an account, it should make the connection with Facebook and bring user back to the Create a Profile screen with their FB profile prepopulated.

**Comment by phuong37** [comment]
that sounds perfect to me, anh @cuong-ubesim! chi @nguyendtt?

**Comment by nguyendtt** [comment]
I think that's fine @cuong-ubesim and @phuong37

**Comment by ThangPk** [comment]
"Another thing is that, after DAR made the connection with FB, before returning me to the rider screen, I received this confirmation "You have already authorized DealARide" (see attached, sorry for bad picture) regardless if I'm a returned user or a first-time user. Is this step necessary and can we eliminate it?"

This is an issue on facebook sdk, it's resolved if having native FB app.

More information below:
http://stackoverflow.com/questions/17725173/how-to-avoid-showing-already-authorized-to-app-dialog-in-android-facebook-sdk

"Found that if native FB app is not installed in device, 'already authorized' window shows up every time i post to FB and it gets resolved by installing the native FB app"

**Comment by phuong37** [comment]
anh @ThangPk - my app crashes every time I click "ok" from the "you have already authorized DealaRide" screen. I have the native app installed and have tried logging in and out of my account.

**Comment by nguyendtt** [comment]
This is now resolved.
