### ISSUE TITLE
[Android] - hotspot for adding a photo should cover the add photo link

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#13]
-need to make sure that users can click the link, "Add Photo +" and not just the image above it
![image](https://cloud.githubusercontent.com/assets/14874365/10138902/c0b2c36a-662a-11e5-8977-8c9669b44119.png)

**Comment by ThangPk** [comment]
Resolved this issue, please wait the next build to verify.

**Comment by phuong37** [comment]
Will verify in next release. Thank you @ThangPk!

**Comment by nguyendtt** [comment]
Issue is resolved.
