### ISSUE TITLE
[Android] - hotspot on account selection screen too small

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#15]
-please make hotspots bigger so that it's easier to select between creating a rider account and driver account.
-if possible, please allow for swiping of the screen

![image](https://cloud.githubusercontent.com/assets/14874365/10138964/f8186a76-662a-11e5-8cc7-c5fccbcf2ef1.png)

**Comment by ThangD** [comment]
Add code to resolve this issue.

**Comment by phuong37** [comment]
Will test in next release. Thank you @ThangD!

**Comment by nguyendtt** [comment]
No swiping but it's much easier now to toggle between Register as Rider and Register as Driver.
