### ISSUE TITLE
[Android] - dar icon too small

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#16]
-dar icon is rendering too small on samsung galaxy s6 edge. see screenshot. 
-change "A" in DealARide to small "a," it should be DealaRide

![image](https://cloud.githubusercontent.com/assets/14874365/10138983/0de7de72-662b-11e5-808b-9b228a09890d.png)

**Comment by trietphamvm** [comment]
Cuong, please add this icon to fix this bug

![image](https://cloud.githubusercontent.com/assets/14874365/10139002/22bc3546-662b-11e5-9a54-508c70bcf68c.png)

**Comment by cuong-ubesim** [comment]
Fixed. Please wait for next release

**Comment by phuong37** [comment]
Will do, thank you anh @cuong-ubesim!

**Comment by phuong37** [comment]
validated!
