### ISSUE TITLE
[iOS]  - App keeps crashing

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#18]
In the process of creating an account, app keeps crashing especially after hitting the back button. This happens for both creating a rider and driver account.
Tested on iPhones 5 and 5c.

**Comment by phuong37** [comment]
chi @nguyendtt, anh @phucdoan - is this still an issue?

**Comment by nguyendtt** [comment]
@phuong37 it hasn't been an issue for me. For you, it still sounds like an issue? Can you try clearing the FB email one more time and reinstall the app, Phuong?

**Comment by phuong37** [comment]
chi @nguyendtt - let's close this one. we have other bugs open for the FB and driver registration. thanks!

**Comment by phuong37** [comment]
validated, closing issue.
