### ISSUE TITLE
[Android] - unable to load main driver options

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#2]
when i click on make offer, ride now, and reserve ride, the tabs do not expand to show the vehicle options.
![image](https://cloud.githubusercontent.com/assets/14874365/10138610/8832673a-6629-11e5-8210-6fbaffd859ea.png)

**Comment by ThangPk** [comment]
@nguyendtt These function are not implemented on this release yet.

**Comment by cuong-ubesim** [comment]
UI got updated, but functionality is not implemented fully. I resolved this item as UI added. Please create another item when you guys find issue on it. Thanks!

**Comment by phuong37** [comment]
ok, yes, UI loads - we will add issues accordingly. thanks!
