### ISSUE TITLE
[iOS] - unable to install on iOS versions 8.1 & 8.3

### ISSUE THREAD

**Issue by phuong37** [trietphamvm/DAR#20]
Team, Thanh L and I were not able to install the app on our phones. We have iOS versions 8.1 & 8.3 and we have already supplied our UDIDs. 
![installation_error](https://cloud.githubusercontent.com/assets/14860705/10153077/79d44ac6-660d-11e5-8eb4-ef1814281b48.PNG)

**Comment by nguyendtt** [comment]
I have version 9.0 on the 5 and 8.4.1 on the 5c and they both installed.

**Comment by trietphamvm** [comment]
Please resend the UDID of this device so that I can check with iOS team?

Thanks
TP

**Comment by tle960** [comment]
Thanh Le - 856667a9f75637b5b89e34e97f88c01ef6b57314

**Comment by phuong37** [comment]
Jim was not able to install either - his UDID is FFFFFFFF60AA863EC645425EB62B3FD6568166EA

**Comment by phuong37** [comment]
Mine/Phuong's is - a16525dd680701dcd59da83fd3d1797b49ce0ac2

**Comment by trietphamvm** [comment]
Added. Please close this ticket after Jim install the app.

Thanks
TP

**Comment by trietphamvm** [comment]
Added, please close after you confirm that can install the app

Thanks
TP

**Comment by phuong37** [comment]
strange - thanh l and I are still unable to install even with new link?

**Comment by trietphamvm** [comment]
I forgot that your iOS must be 8.4 or higher.

Thanks
TP

**Comment by phuong37** [comment]
thank you! we will install the software update and retry.

**Comment by phuong37** [comment]
This has been resolved. Thanks team!
