### ISSUE TITLE
[iOS + Android] - Stronger password required

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#21]
Tested on iOS but perhaps this is an overall enhancement.  User was able to enter "1234" as a password.  A stronger password should be required.  Perhaps at least 8 characters with at least 1 number and an upper case letter.

**Comment by cuong-ubesim** [comment]
Please make a rule to define strong password on server side first, then Android and iOS will display hint

**Comment by trietphamvm** [comment]
Got it

Thanks
TP

**Comment by trietphamvm** [comment]
I just update the API, here is the rule: at least 7 characters which at least 1 upper case, 1 lower case and 1 digit

@cuong-ubesim , @phucdoan please add the hint if user type the weak password as below:

"Password must be at least 7 characters and contains at least 1 number, 1 upper-case and 1 lower-case letter."

**Comment by cuong-ubesim** [comment]
Added this hint to Android app

**Comment by nguyendtt** [comment]
Now works for both iOS and Android.
