### ISSUE TITLE
iOS bug - unable to request rides

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#22]
After inputting pickup and dropoff locations, user is unable to select "make offer" "request ride" or "reserve ride".  The buttons are not functional. Tested on iPhones 5 and 5c.

**Comment by phuong37** [comment]
Oh Trinh, Thanh mentioned that the this feature has not been implemented yet.

**Comment by trietphamvm** [comment]
This version still not implement this feature chi Trinh. Please wait more time for that function to work.

Thanks
TP

**Comment by nguyendtt** [comment]
Got it. I'll go ahead and close this for now.
