### ISSUE TITLE
[Android] - compatibility issue with older/less popular phones

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#23]
Logging this as a bug for now since I'm not sure if the issues are the phones that I have.

I got a hold of some older Android devices today, a Motorola Moto X and an HTC One M8 and got the app to install.  However upon launching the app, i was greeted with the "No Valid Google Play Services APK found." message.  The HTC has Android 4.17.605.5 version and the Moto X has 5.0 version.  According to Uber site,as long as the phones has 4.0 or above version, they should be compatible.  They also say most phones manufactured in 2013 or later should work and these are.  I think for compatibility, we can borrow Uber's criteria: http://drive.uber.com/oh/faqs/what-phones-are-compatible-with-the-uberpartner-app/
![error](https://cloud.githubusercontent.com/assets/14857908/10231309/4552a034-683f-11e5-83f3-bc1698170be1.JPG)

**Comment by nguyendtt** [comment]
Sorry attached the wrong image, right screenshot should be attached now @trietphamvm @cuong-ubesim

**Comment by cuong-ubesim** [comment]
Please make sure that your device has at least Google Play Services 7.5

You can check the current version of Google Play Services by going to Settings > Applications > Application manager > Google Play Services

**Comment by nguyendtt** [comment]
Updated to Google Play Services version 8.1.15 and the app can be launched now. Thanks.
