### ISSUE TITLE
iOS bug - unable to complete driver's account after logging back in

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#24]
Not sure if this is a bug or it's just not completely built out but after the app crashes during the process of inputting driver's license, after logging back in (even after reinstalling app), there's not a way to continue the process to input the insurance information.  Sometimes, user gets the "Under Constructure" screen after logging back in.
![img_8495 1](https://cloud.githubusercontent.com/assets/14857908/10153941/a75b099c-661e-11e5-8e06-952e342d4946.PNG)

**Comment by trietphamvm** [comment]
This is the main screen of driver which we don’t implement yet. If you register as driver, you will have difference main screen against rider.

Thanks
TP

**Comment by nguyendtt** [comment]
Got it, but I was not able to complete the registering process yet, only got through adding a driver's license and haven't got to adding insurance yet.

**Comment by trietphamvm** [comment]
We will fix the crash issue chi Trinh. In case you want to change the driver information, after registering, you can edit that information in profile which will be added.

Thanks
TP

**Comment by nguyendtt** [comment]
OK, please close this ticket if you think that's the appropriate action. Thanks Triet.

**Comment by trietphamvm** [comment]
Ok chi
