### ISSUE TITLE
[iOS] - Email/Phone Number should be unique to each profile

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#25]
Tested on iPhones 5c.  I was able to use the exact same email, password and phone number to create an account again. I did not receive another confirmation email but did get another mobile confimation code. For testing purposes, it would be great if there's a way for us to delete test accounts from the system so we can keep using the same email accounts to create/recreate profiles however for real users, email/phone should be unique to each profile.  

Note: Phuong confirmed that she was unable to create a different account using the same email on Android.

**Comment by trietphamvm** [comment]
This should be a bug. We will fix. Thanks chi.

Thanks
TP

**Comment by nguyendtt** [comment]
I have updated it as a bug. Thanks.

**Comment by phuong37** [comment]
Just a quick note - Android validates against email. I was not able to create an account yesterday with the same email. :)

**Comment by nguyendtt** [comment]
Got it. Thanks Phuong.  I will update the ticket.  Unrelated but is there a way to tag someone in the comment?

**Comment by phuong37** [comment]
@nguyendtt

**Comment by nguyendtt** [comment]
Thanks @phuong37 .  That's so simple.  I was stuck in Jira mindframe doing [~phuong37]. :)

**Comment by trietphamvm** [comment]
I just update the server API to make sure the phone number is unique. I checked database, chi Trinh made a mistake where the email is difference. 

@cuong-ubesim  and @phucdoan, please update your side to check phone number as well

**Comment by phuong37** [comment]
anh @phucdoan and anh @cuong-ubesim, can you please add validation to make the phone number 10 digits only? US is 10 digits. thank you!

**Comment by trietphamvm** [comment]
Let me update on the API, the mobile just use it.

**Comment by phuong37** [comment]
perfect! thank you anh @trietphamvm!

**Comment by nguyendtt** [comment]
Question on this, if a user signs up for a rider account, then later signs up for a driver account, can they use the same email address/phone number or they have to be different?  I think later on we will have the option for rider to sign up as a driver but can you confirm how it should work now? Thanks. @trietphamvm

**Comment by cuong-ubesim** [comment]
Rider has to use BECOME DRIVER functionality to upgrade her account from RIDER to DRIVER, chi @nguyendtt

**Comment by nguyendtt** [comment]
Got it, that answers my question.  So from the home screen, they will have to use a different email address/phone number. Thanks @cuong-ubesim

**Comment by phuong37** [comment]
Wait sorry, I thought it was one account anh @cuong-ubesim, chi @nguyendtt, and @trietphamvm

**Comment by phuong37** [comment]
You create one rider account and "upgrade" to driver to access both?

**Comment by cuong-ubesim** [comment]
That's correct, @phuong37 . After upgrading to DRIVER, the user can work as either RIDER or DRIVER with one account. It depends on which option the user wants.

**Comment by nguyendtt** [comment]
Sounds like there's not a screen created for that @phuong37 ? To choose between Rider and Driver account once you log in. Will this be a launch feature?

**Comment by phuong37** [comment]
Hi chi @nguyendtt - you can log out and in as rider/driver in the side nav. We just need to make sure that the updated side nav from the google drive is implemented, not the current one. I need to log a bug for that, sorry!

**Comment by nguyendtt** [comment]
I see that screen now @phuong37 . Thanks.

**Comment by nguyendtt** [comment]
This is now resolved.
