### ISSUE TITLE
[iOS] - unable to get past payment info screen

### ISSUE THREAD

**Issue by phuong37** [trietphamvm/DAR#28]
strange - i used the 4242 number but still no luck. it just hangs.
i have an iphone 6 plus and just upgraded to iOS 9.0.1
![img_3823](https://cloud.githubusercontent.com/assets/14860705/10156318/a4666c66-6634-11e5-9c0f-24adb7582967.PNG)

**Comment by nguyendtt** [comment]
Is this for creating a rider or driver account @phuong37 ?  I had no issue with this screen yesterday when registering for both rider and driver, however today when I try to create a driver account, it hangs too but the message is "Loading..."

**Comment by phuong37** [comment]
@nguyendtt - both, i believe the first 3 screens are the same for riders and drivers including the payment screen but please double-check. :)

**Comment by trietphamvm** [comment]
I'm sorry about this @phuong37  and chi Trinh @nguyendtt. This issue caused by the server is just updated for checking the strong password and unique phone number.

To workaround this issue, I will delete the accounts that use Phuong's number or chi Trinh's number then you can re-register your new account and make sure you create a strong password: at least 7 characters, 1 digit, 1 upper case and 1 lower case.

Both android and ios @cuong-ubesim  and @phucdoan, please fix this bug as soon as possible.

**Comment by nguyendtt** [comment]
They look the same but I'm not sure if they are the same on the backend @phuong37 @phucdoan @trietphamvm .  Today, when singing up for driver account, I got "Loading..." on driver side and "Finishing sign up...." for rider side.

**Comment by nguyendtt** [comment]
Got it @trietphamvm . Yes please let us know when it's ready to test again.

**Comment by phuong37** [comment]
i will re-register once it's ready! thank you anh @trietphamvm!

**Comment by trietphamvm** [comment]
you are ready @phuong37. I just delete your one account on server. Please try again, remember to have strong password.

**Comment by nguyendtt** [comment]
I am able to get through with a strong password but the app crashes when it gets to the insurance screen, same experience yesterday. I will log a bug for that.

**Comment by phuong37** [comment]
hmm, i tried but am seeing an X when i submit. 7 characters with 1 number, 1 cap, and 1 lowercase. i even tried more than 7 characters...

**Comment by phuong37** [comment]
nevermind, it's because i tried to use my gmail email and not yahoo. :) it's working now - thank you!!

**Comment by trietphamvm** [comment]
OK Phuong, this bug will be get rid in next release

**Comment by phuong37** [comment]
awesome, closing bug. thank you!

**Comment by trietphamvm** [comment]
Please do not close it when you do not receive the fix @phuong37

**Comment by phuong37** [comment]
good point, i will validate in the next release and then close. thanks!

**Comment by phuong37** [comment]
please delete jim's account - i will have him create a new account with a stronger password. thanks!

**Comment by trietphamvm** [comment]
Still don't see Jim's account yet. I think he will be fine

**Comment by phuong37** [comment]
he texted me saying that the screen is hanging on the payment screen. @nguyendtt, running to meeting. would you mind helping him? thank you!

**Comment by phuong37** [comment]
chi @nguyendtt and i have validated and we are able to get past the payment screen, closing bug.
