### ISSUE TITLE
[iOS] - Route button on main rider screen?

### ISSUE THREAD

**Issue by phuong37** [trietphamvm/DAR#30]
hi team, this is a question for all. as we're building out the main rider screen, i noticed that there's a route button, i'm just wondering if we need it and here's why -

-i agree that we have to guide a user to hit enter but can we do it in the iOS keyboard instead? see where it says "Search" below? just a suggestion but would love to get your thoughts
-remember that all the drivers cars will be loaded as cars on the map when they get to 
-the user must select a driver (submit request) first before it can route?
-we have the route function in the next screen after the users chooses a driver but i'm definitely open to ideas :)

just want to get everyone's thoughts.

anh @trietphamvm - side note: i think we need to revisit if we need drop-off as a core function (maybe feature) - see uber and lyft. let me email larger team. 

thanks!
phuong

![img_3826](https://cloud.githubusercontent.com/assets/14860705/10173131/91d42508-6697-11e5-9fdb-3bd4b6d848a1.PNG)

**Comment by phuong37** [comment]
anh @trietphamvm, i've been thinking through this and we do need to the drop-off location in order to display the prices. i was testing our competitors and it was not required so i wanted to explore some more. let's leave it as is for now. thanks!

**Comment by trietphamvm** [comment]
the other system don't require the drop-off, but for our app, that is required I think. Because driver can't bid if we don't have the drop-off.

The route will be displayed on the map when user select pick-up and drop-off plus the distance and estimation time before making a request.

That's my initial thought. Any comment on this?

**Comment by phuong37** [comment]
i completely agree. let's leave for now but explore later. thank you!!

**Comment by phuong37** [comment]
love how this was resolved. thank you!
