### ISSUE TITLE
[Email] - Please update email template with new color scheme

### ISSUE THREAD

**Issue by phuong37** [trietphamvm/DAR#31]
Sorry, we just got a chance to update the email template with the new color. Please see attached. It's also in the DAR google drive.

Thank you!
Phuong

![dar_email_update](https://cloud.githubusercontent.com/assets/14860705/10184746/0e72218e-66f5-11e5-8988-897cb27c9e5c.png)

**Comment by trietphamvm** [comment]
Which color did you change? The "A" character in DealARide need to be "a" as well. Thanks.

**Comment by phuong37** [comment]
Color should be - #28AAE0

![dar_email_v3_updated](https://cloud.githubusercontent.com/assets/14860705/10184855/8c060e66-66f6-11e5-960f-abfa7bd57826.png)

Updated in Google Drive as well.

Thanks!
Phuong

**Comment by trietphamvm** [comment]
@phuong37 @nguyendtt , this issue is fixed at the API side, please verify again.

I just create a new Label "Resolved" for easy tracking. Both of you only verify the resolved one when receive a new release. Then close it if it's fixed, or change the label from Resolved to Re-open

This tool is not professional, so we should try the label for status tracking as workaround.
Thanks,

**Comment by phuong37** [comment]
thank you anh @trietphamvm! for some reason, i can't view the email from my phone. i can view it on my desktop web browser though - looks great! any ideas why it might not be rendering on mobile? the new "Resolved" label is a great idea!

**Comment by trietphamvm** [comment]
You mean the emails from your account?

**Comment by nguyendtt** [comment]
Yes, @trietphamvm .  The confirmation email sent out from DAR renders blank on my phone also.  Looks fine on desktop.  Another question for both of you, will we have different confirmation emails for rider and driver? I remember getting the same exact email after registering for a driver account.

**Comment by trietphamvm** [comment]
You are correct, I will check the rendering on mobile tomorrow. @Phuong, can you give me difference template for rider and driver?

**Comment by phuong37** [comment]
Thanks chi @nguyendtt! Anh @trietphamvm, yes, will work on that today. Thanks!

**Comment by trietphamvm** [comment]
The blank email is fixed @phuong37. Please verify again and close this bug.

**Comment by nguyendtt** [comment]
I have verified and this is now working accordingly on mobile @phuong37 . THanks @trietphamvm

**Comment by nguyendtt** [comment]
Sorry, I meant the email renders on mobile correctly.  Reopened so @phuong37 can verify the new color scheme.

**Comment by phuong37** [comment]
Sorry, for the delay! Looks great on mobile, anh @trietphamvm and chi @nguyendtt! thanks for validating chi @nguyendtt, if sign off on it, please go ahead and close. please don't wait for me, i'm only here to provide support. :)

**Comment by nguyendtt** [comment]
Understood @phuong37. I only reopened since I realized the main reason for the ticket is the color scheme updating. :)
