### ISSUE TITLE
[Android + iOS] - Raleway Numeric font is not aligned

### ISSUE THREAD

**Issue by tle960** [trietphamvm/DAR#32]
Hi TP,

I have a quick question that hopefully you have the answer to.  Railway is a great font but one issue with this font is that its numeric alignment is off. Is it possible to use another font just for numbers? That would resolve this issue quickly and efficiently.

Thanks,
Thanh

**Comment by trietphamvm** [comment]
Do you have any recommendation for another font?

**Comment by tle960** [comment]
Yes, can we use Lato (google font) just for numbers? That would be great.

Thanks Tree!

**Comment by cuong-ubesim** [comment]
Applied Lato google font on Android. It is really great font.

**Comment by trietphamvm** [comment]
Please apply on ios as well @phucdoan

**Comment by nguyendtt** [comment]
@tle960 @phuong37 can you help me validate this ticket? I want to make sure the correct font is applied.

**Comment by tle960** [comment]
The Lato font is correct. Thank you all!
