### ISSUE TITLE
[Email] - Driver registration email

### ISSUE THREAD

**Issue by phuong37** [trietphamvm/DAR#34]
chi @nguyendtt and anh @trietphamvm. the driver email has been uploaded to the google drive. thanks!

![dar_driver_email_v1](https://cloud.githubusercontent.com/assets/14860705/10212024/95902a26-67ae-11e5-8301-cafd50ffc345.png)

**Comment by nguyendtt** [comment]
Looks great @phuong37

**Comment by phuong37** [comment]
I received the driver email, closing issue.
