### ISSUE TITLE
[Android] Facebook Profile image appears very pixilated on DAR profile

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#35]
Profile picture imported over to DAR profile looks very pixilated both on the Create a Profile screeen and side nav.  Please see attached.
![profile](https://cloud.githubusercontent.com/assets/14857908/10270269/c0dfe3da-6aa9-11e5-9f33-73ffc5b61c98.png)

**Comment by cuong-ubesim** [comment]
Chi @nguyendtt  Can you try with another picture to see whether it happens? If this bug is still there, share the picture you use already please. Thanks!

**Comment by nguyendtt** [comment]
Hi @cuong-ubesim , I tried creating a brand new FB account with a different picture and i'm still experiencing the same issue with pixilated image. Please see attached.  I also discovered another bug with signing up with FB that I will log separately.
![screenshot_2015-10-05-15-44-20](https://cloud.githubusercontent.com/assets/14857908/10294619/c07f171a-6b78-11e5-9eb3-1831fbcfcbf5.png)

**Comment by nguyendtt** [comment]
Here are the 2 pictures, saved from Facebook.
![stella](https://cloud.githubusercontent.com/assets/14857908/10294709/3d14ca22-6b79-11e5-93f7-bb011fa61bb3.jpg)
![trinh](https://cloud.githubusercontent.com/assets/14857908/10294711/3f6e6cc4-6b79-11e5-8b3f-f7fbcbefe0db.jpg)

**Comment by nguyendtt** [comment]
This is no longer an issue. Closing.
