### ISSUE TITLE
[Android] Drop down menu icon is cut off on side nav

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#36]
On the side nav, the Drop Down menu icon on the upper left is cut off.  Also please update "Adv Listings" to just "Ad Listings". Please see attached.
![profile](https://cloud.githubusercontent.com/assets/14857908/10270288/0524987e-6aaa-11e5-8eba-9c65e3ac2aea.png)

**Comment by cuong-ubesim** [comment]
Fixed. Thanks!

**Comment by nguyendtt** [comment]
Thanks @cuong-ubesim will test again when the new build is out.

**Comment by nguyendtt** [comment]
Side nav is now replaced with the dots so this is no longer an issue.
