### ISSUE TITLE
[iOS + Android] Update "Phone number" field  to "Mobile phone number"

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#39]
Chatted with @trietphamvm  on this. On the create profile screen for both Rider and Driver, please update "Phone number" to "Mobile phone number".  I was able to enter my office (landline) number for my profile and landline numbers cannot receive text confirmation code.  Since the format for landline and mobile are the same in the US, it will be difficult to detect if the number is not mobile.  The update is to encourage users to use their mobile number. 

Tagging both @phucdoan and @cuong-ubesim since I can only assign one developer at the time on the ticket.

**Comment by cuong-ubesim** [comment]
Done on Android

**Comment by nguyendtt** [comment]
Thank you @cuong-ubesim

**Comment by nguyendtt** [comment]
This is resolved. Closing.
