### ISSUE TITLE
[Android] - driver registration field validation and verification

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#4]
Thanh and team - we need to add validation and error messaging to some of the form fields.

-If under 21 yrs old, display message: Sorry, you have to be at least 21 years of age to register as a Driver.
-address, state and zip need to be verified by postal system
-drivers license number and state need to be verified by US DMV (department of motor vehicle)
-insurance needs to be validated as well?

**Comment by trietphamvm** [comment]
Phuong @phuong37, can you give me the service that we will use to validate driver license number and state. The service to validate insurrance as well. Thanks.

**Comment by phuong37** [comment]
Hi Thanh, this one is tricky. We have to use some kind of ID verification service like jumio or veratad, etc. as for insurance, we will have to do some research on DMV (US Department of Motor Vehicle) type APIs. I'm not sure that any of the services will be free.

**Comment by phuong37** [comment]
Maybe not jumio but netverify

**Comment by trietphamvm** [comment]
Yes, I searched some service, and seem they have the separated API for each state. If so, the code for checking will be complicated. I just want to know that it’s really necessary?

Thanks
TP

**Comment by phuong37** [comment]
i would say yes but we can open the discussion to the team if you want. if we don't verify driver's license and insurance, i think it could be a very big mess for us in the future. even if we're not performing background checks, verifying that a user has a valid driver's license and valid auto insurance is a minimum. what do you think?

**Comment by nguyendtt** [comment]
I agree that it needs to be open for discussion, perhaps it's a question for Buruk since he drives for Lyft.

**Comment by phuong37** [comment]
@trietphamvm - should we validate in Colorado and California first? Lam said that he has an car insurance contact now, I know they can validate this information on their system. Maybe we can integrate with their API?

**Comment by trietphamvm** [comment]
Can you work with them to give me the API?

Thanks
TP

**Comment by phuong37** [comment]
i talked to lam, he will talk to the insurance guy on wednesday. thanks!

**Comment by trietphamvm** [comment]
That’s cool Phuong.

Thanks
TP

**Comment by phuong37** [comment]
anh @trietphamvm, chi @nguyendtt - i talked to anh lam and he said that we will make each user certify that they are disclosing truthful information. he will have a lawyer draft that up closer to launch. for now, i would suggest that we just do validation on the formatting of licenses in CO and any other state that we're launching? what do you think? so if they select CA, it will require 8 digits, alphanumeric. 

chi @nguyendtt - i don't have my old CO license on me, can you please add the formatting here?

no verification will be required at this time. just some field validation. thanks!

**Comment by trietphamvm** [comment]
Got it @phuong37. Please give me the format at CO ASAP

**Comment by nguyendtt** [comment]
So sorry I missed this. My CO license is 94-196-2528

**Comment by nguyendtt** [comment]
@trietphamvm

**Comment by phuong37** [comment]
Thank you chi @nguyendtt!

**Comment by trietphamvm** [comment]
@phuong37, please confirm again so that I add the logic for checking the driver license number:

- If CO, it's always 9 digits
- If CA, it's always 8 digits and how many alphanumeric?

**Comment by trietphamvm** [comment]
I already add this checking logic for driver license number on API. Please update at mobile side @phucdoan  and @cuong-ubesim. Phuc, let Cuc help you to handle this.

**Comment by cuong-ubesim** [comment]
Done on Android

**Comment by phuong37** [comment]
Anh @trietphamvm, please see below -

If CO, it's always 9 digits - all numeric
Format is 12-123-1234 (XX - XXX - XXXX)

If CA, it's always 8 digits - any combination of numbers and letters only, no special characters
Format is XXXXXXXX

Let me know if you need any more details.

Thanks!
P

**Comment by trietphamvm** [comment]
I found this rule already Phuong, I also add for all states of US. Please check if you have enough data.

Thanks
TP

**Comment by phuong37** [comment]
Ok perfect, will do. Thanks!

**Comment by nguyendtt** [comment]
Closing based on Phuong's conversation with Lam that we cannot verify.
