### ISSUE TITLE
[iOS] cannot clear account signed up with Facebook 

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#43]
Please let me know if there's a way to clear my account when Facebook login was used.  I used the link Triet provided http://dealaride-staging.azurewebsites.net/api/user/delete?email=nguyendtt@hotmail.com and it doesn't seem to clear.  Can you help?

**Comment by phucdoan** [comment]
Please update URL to delete existed account to:
http://dealaride-staging.azurewebsites.net/api/user/delete?email=nguyendtt@hotmail.com 
=> http://dealaride-qa.azurewebsites.net/api/user/delete?email=nguyendtt@hotmail.com 

Sry chi Trinh, we update to new server on this build.
This is missing.

**Comment by nguyendtt** [comment]
THis is no longer an issue. Closing. Using this link to clear for both email and phone.
http://dealaride-qa.azurewebsites.net/api/user/delete?key=nguyendtt@hotmail.com
