### ISSUE TITLE
[Android] - adding address makes the app hang

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#6]
on main rider screen, when i try to add an address, it hangs and the spinner keeps spinning.
![image](https://cloud.githubusercontent.com/assets/14874365/10138735/13e6c348-662a-11e5-9ceb-585803e5db8d.png)

**Comment by cuong-ubesim** [comment]
Fixed. Please wait for next build. Thanks!

**Comment by cuong-ubesim** [comment]
Rendering driving direction between pick up and drop off locations as well. The app will not be hang anymore

**Comment by phuong37** [comment]
Thanks anh @cuong-ubesim! I will test in next release.

**Comment by nguyendtt** [comment]
The issue seems to be resolved.
