### ISSUE TITLE
[Android] - minor visual adjustments

### ISSUE THREAD

**Issue by trietphamvm** [trietphamvm/DAR#8]
-update logo to new logo (brighter blue)
-smaller top dar logo after home screen needs to be centered (scoot to the left a bit).

![image](https://cloud.githubusercontent.com/assets/14874365/10138786/46687f96-662a-11e5-80f6-9a31883738ce.png)

**Comment by ThangPk** [comment]
Update the code. Please wait to next build.

**Comment by ThangPk** [comment]
Update the code, please wait to next build.

**Comment by phuong37** [comment]
Awesome! Thank you @ThangPk!

**Comment by nguyendtt** [comment]
Looks good to me.
