### ISSUE TITLE
[iOS + Android] There is not a way to update email address

### ISSUE THREAD

**Issue by nguyendtt** [trietphamvm/DAR#92]
When clicking Edit Profile on the side nav, i'm only able to update my picture, First, Last Names and phone number but not email address.  I also feel that when a phone number or email is updated, a confirmation code should be sent out again to verify.  Can we think through about this flow, @tle960 ?

**Comment by nguyendtt** [comment]
![img_3273](https://cloud.githubusercontent.com/assets/14857908/10568924/c8f540dc-75db-11e5-81b4-622481088006.PNG)

**Comment by trietphamvm** [comment]
Email is not allowed to change.

**Comment by trietphamvm** [comment]
Not allow to do this.

**Comment by nguyendtt** [comment]
Is there a reason for this @trietphamvm @phuong37 ?

**Comment by trietphamvm** [comment]
This is very popular in almost app when the email is the identity of the user chi Trinh.

**Comment by phuong37** [comment]
chi @nguyendtt - i believe email is the unique identifier that creates the account, thus, it must be locked for each account.

**Comment by nguyendtt** [comment]
Ok that's fine, I will close this ticket.  @trietphamvm @phuong37
